#!/bin/bash
set -e

# Azure Migration Phase 2 Deployment Script
# Generated by Antigravity

# Secrets (Retrieved from Key Vault / Environment)
POSTGRES_PASSWORD='CTXeco2026!Secret'
REGISTRY_USERNAME='derekbmoore'
REGISTRY_PASSWORD="${REGISTRY_PASSWORD}"
ZEP_API_KEY='placeholder-zep-key'
AZURE_AI_KEY='cf23c3ed0f9d420dbd02c1e95a5b5bb3'
FOUNDRY_ENDPOINT='placeholder-foundry-endpoint'
FOUNDRY_PROJECT='placeholder-foundry-project'
FOUNDRY_KEY='placeholder-foundry-key'
ELENA_AGENT_ID='placeholder-elena-agent-id'
ANTHROPIC_API_KEY='placeholder-anthropic-key'
GEMINI_API_KEY='placeholder-gemini-key'
GITHUB_TOKEN='placeholder-github-token'
VOICELIVE_API_KEY='placeholder-voicelive-key'

echo "Starting Phase 2 Deployment to ctxeco-rg..."

az deployment group create \
  --name ctxeco-deployment \
  --resource-group ctxeco-rg \
  --template-file infra/main.bicep \
  --parameters infra/environments/ctxeco/parameters.json \
  --parameters \
    postgresPassword="$POSTGRES_PASSWORD" \
    registryUsername="$REGISTRY_USERNAME" \
    registryPassword="$REGISTRY_PASSWORD" \
    zepApiKey="$ZEP_API_KEY" \
    azureAiKey="$AZURE_AI_KEY" \
    azureFoundryAgentEndpoint="$FOUNDRY_ENDPOINT" \
    azureFoundryAgentProject="$FOUNDRY_PROJECT" \
    azureFoundryAgentKey="$FOUNDRY_KEY" \
    elenaFoundryAgentId="$ELENA_AGENT_ID" \
    anthropicApiKey="$ANTHROPIC_API_KEY" \
    geminiApiKey="$GEMINI_API_KEY" \
    githubToken="$GITHUB_TOKEN" \
    voiceliveApiKey="$VOICELIVE_API_KEY" \
  --output table

echo "Deployment initiated. Check status in Azure Portal."
